
server:
  port: 7577
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /templates
      suffix: .html
#  2021.10.03 docker-compose 테스트 위해 주석 처
#  datasource:
#    url: jdbc:h2:mem:legacydb;MODE=MySQL
#    platform: h2
#    username: test
#    password: test
#    driverClassName: org.h2.Driver

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3309/test_db
    platform: mysql
    jdbc-url: jdbc:mysql://localhost:3307/dev_st_db?characterEncoding=UTF-8
#    jdbcUrl: jdbc:mysql://localhost:3309/test_db
    username: root
    password: root

  # jpa
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    
  
  #devtool      
  devtools: 
    livereload:
      enabled: true
      
  #mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email.properties.username}
    password: ${email.properties.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis-st:
      host: localhost
      port: 6381
      database: 1
      prefix: st
  #redis
  redis-legacy:
    host: localhost
    port: 6379
    database: 1
    prefix: legacy
#security:
#  basic:
#    enable : false
#    
#management:
#  security:
#    enabled: false  