
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /templates
      suffix: .html
#  2021.10.03 docker-compose 테스트 위해 주석 처
#  datasource:
#    url: jdbc:h2:mem:legacydb;MODE=MySQL
#    platform: h2
#    username: test
#    password: test
#    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        format_sql: true
    
  
  #devtool      
  devtools: 
    livereload:
      enabled: true
      
  #mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email.properties.username}
    password: ${email.properties.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #redis
  redis:
    host: localhost
    port: 6379
#security:
#  basic:
#    enable : false
#    
#management:
#  security:
#    enabled: false  