version: "3"

services: 
  database:
    image: mysql:5.7
    environment:
      MYSQL_USER: test_user
      MYSQL_DATABASE: test_db
      MYSQL_PASSWORD: test_pw
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./database/spring_social/:/var/lib/mysql"
    ports:
      - "3306:3306"
    container_name: st_mysql
#    networks:
#      - backend-network

  redis:
    container_name: st_redis
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
