version: "3.7"

services:
  st_mysql:
    container_name: st_mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
    volumes:
      - "./database/spring_social/:/var/lib/mysql"
    ports:
      - "${HOST_MYSQL_PORT}:${CONTAINER_MYSQL_PORT}"

  redis:
    container_name: st_redis
    image: redis:latest
    command: redis-server
    ports:
      - "${HOST_REDIS_PORT}:${CONTAINER_REDIS_PORT}"

